dist: xenial
language: python
python:
  - 3.6
  - 3.7
notifications:
  email:
    - nick.hand@phila.gov
env:
  global:
    - secure: NwECQbVV0OfPPZGE9eXPGaRwnF/WLL09EKqkMTsOsvIuKhizVaXg7PHHmcrD+cIKyftFJGfNYHL1Ea4RD88HFc4NmZqIfuPwtnzb9Gmr2g2MNpmS0GJKhqjytWlVTcM9JIz2NmQFX6HHW98cCcDp/v/obx9he0GjNAkzIdWHwyeet/5wvhHfNBDRV/cEFWQyNRgFPkq5ARbLC2+FU4u7O8HATBXdglgo98P2iDJI9n+1YUNoijcUNI+F6OKCepqzdf1Ir0559o3+mjfHgiEBLLlf/ozdFux/HWftXE7I5EikBKvotg+AtoWFmV6YFjXWKVTeLkJTFxSStVru84Wksird0tyFpqlE67xXDj/zxbzmqBp34zV6xPsqyb6TtdSG1G9x9ulMn/7mnUKvJ0B+c2x6HiMz4st3gJ9SXXwYZQI56d0VtACWtRDBAtoehIpuOnVsrSm/pOLRgWj4lnzpGSb6s+tjgTHgkGUqjN4ZBVGV6v4EvuzX8GPXQVY/16gXrunKH5aVMKvT+Q0aU8PLqc5WEyCqXzNUxTdzsGvTINdafO61F2MvF0jpiJzlMaAvXLlLX4WjR9x5kiVBjLBKMidY70J41PVmY/3lnUJGYdGt39kxgqmzNGn7LwP0tmMamCadFXg5HIkGa8Jatkybs1nZzmHCQTjvoGJZCj/MWbo=
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.conda"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - "./miniconda.sh -b -p $HOME/miniconda"
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION conda-build jinja2 anaconda-client
  - pip install .[dev]
script:
  - py.test . --cov esri2gpd
after_success:
  - coveralls
  - chmod +x deploy_anaconda.sh
deploy:
  matrix:
    - provider: pypi
      distributions: sdist
      user: controllerphl
      password:
        secure: PF3np0g8Mt9EFs56pJKv128YsrSukStAfwC0qjVZgwJejf2Yt8Bl8TR2jDghUAO+Aaeu7j5oOoRDfw6z2/GuO0iV/vwH/cfvxUnNdI9TsjzKWvm7RLubyHdW/LrzbPwXnz+1gQy6cJ+5OxCL9m9CFECz7J2nnHmOtD4ri8+5oStGfQcMvigIUvISbdCaM2XDtfoVdOZ9F/ukRNaKSdXC0FT5eDwiaj6SrCFhPSIEbBG+LuZODhreqI2QpJtd18AZoJbbuvE20FWhz371JyHE4rtyOb6wCydw2gsazntNYGLTxQMGD+aZZW4OgtvLjwacaKDKEn/doGTH4+GRJ4XU9Njt/RkHf3zUsR5RROxyP4nla+6a0jSlhHhN23plfV8RdGbhKbk+JNWKSKlGPUAOop9sFsKklPIMzw+T5ekyX2U87vSy6nkjUeJ8k4gkdzUGdOAktUo7SWhFibTm/N9Gm/y02obv8L3SYmZumZnEUlFsPzCXzAt5mYodFB84pRmk/GLd5mVLjfhr8HMJluTMsacywF1U1iSPYSe9/VvT1a0Jt2Ir7WBw4kmMg9SNjqKBNGGVQM/+PnV2/9omo/irS1/BTReo/zhfTQudbY/i0YxS7e+aGLLlpoSwl7qciNk6U5hCW/++z2sU7cPOiEGYM+m50utl2X1I9oxGFw4g/5o=
      skip_existing: true
      on:
        condition: $TRAVIS_PYTHON_VERSION = "3.7"
    - provider: script
      script: "./deploy_anaconda.sh"
      skip_cleanup: true
      on:
        condition: $TRAVIS_PYTHON_VERSION = "3.7"
